// ═══════════════════════════════════════════════════════════════════════════════
// AURA ARENA — All Disciplines + Sub-Disciplines + Drills
// Every genre, every style, every tradition — fully specified
// ═══════════════════════════════════════════════════════════════════════════════

import type {
  Discipline,
  DisciplineId,
  Drill,
  MediaPipeTask,
  ScoringWeights,
  SubDiscipline,
  Tier,
  TierId,
} from "@types";

// ─── HELPERS ──────────────────────────────────────────────────────────────────

const drill = (
  id: string,
  name: string,
  description: string,
  difficulty: 1 | 2 | 3 | 4 | 5,
  duration: number,
  rhythmBPM?: number,
  styleNote?: string,
  nameLocal?: string,
): Drill => ({
  id,
  name,
  nameLocal,
  description,
  difficulty,
  duration,
  targetKeypoints: [],
  rhythmBPM,
  styleNote,
});

// ─── SCORING WEIGHT PRESETS ────────────────────────────────────────────────────

const WEIGHTS = {
  dance: {
    accuracy: 0.25,
    stability: 0.15,
    timing: 0.3,
    expressiveness: 0.2,
    power: 0.05,
    balance: 0.05,
  } as ScoringWeights,
  classical: {
    accuracy: 0.3,
    stability: 0.1,
    timing: 0.25,
    expressiveness: 0.25,
    power: 0.05,
    balance: 0.05,
  } as ScoringWeights,
  boxing: {
    accuracy: 0.3,
    stability: 0.2,
    timing: 0.25,
    expressiveness: 0.05,
    power: 0.15,
    balance: 0.05,
  } as ScoringWeights,
  martial: {
    accuracy: 0.35,
    stability: 0.2,
    timing: 0.2,
    expressiveness: 0.1,
    power: 0.1,
    balance: 0.05,
  } as ScoringWeights,
  yoga: {
    accuracy: 0.3,
    stability: 0.1,
    timing: 0.15,
    expressiveness: 0.15,
    power: 0.05,
    balance: 0.25,
  } as ScoringWeights,
  gymnastics: {
    accuracy: 0.35,
    stability: 0.15,
    timing: 0.2,
    expressiveness: 0.15,
    power: 0.05,
    balance: 0.1,
  } as ScoringWeights,
  fitness: {
    accuracy: 0.3,
    stability: 0.2,
    timing: 0.25,
    expressiveness: 0.05,
    power: 0.15,
    balance: 0.05,
  } as ScoringWeights,
  bodybuilding: {
    accuracy: 0.4,
    stability: 0.1,
    timing: 0.15,
    expressiveness: 0.25,
    power: 0.05,
    balance: 0.05,
  } as ScoringWeights,
  calisthenics: {
    accuracy: 0.35,
    stability: 0.25,
    timing: 0.2,
    expressiveness: 0.05,
    power: 0.1,
    balance: 0.05,
  } as ScoringWeights,
};

// ─── DANCE SUB-DISCIPLINES ─────────────────────────────────────────────────────

export const DANCE_SUB_DISCIPLINES: SubDiscipline[] = [
  // ── Indian Classical ──────────────────────────────────────────────────────
  {
    id: "bharatnatyam",
    name: "Bharatnatyam",
    nameLocal: "பரதநாட்டியம்",
    parentDiscipline: "dance",
    icon: "Sparkles",
    color: "#f59e0b",
    origin: "Tamil Nadu, India",
    description:
      "Ancient classical dance from Tamil Nadu. Emphasis on Abhinaya (expression), Nritta (pure dance), Nritya (expressive dance).",
    rhythmBPM: 72,
    coachingStyle: "precise and spiritual",
    scoringWeights: WEIGHTS.classical,
    drills: [
      drill(
        "bn-tatkar",
        "Tatkar (Footwork)",
        "Basic rhythmic footwork – Tatkar to 4 counts",
        1,
        120,
        72,
        "Keep spine straight. Weight on balls of feet.",
        "தட்கர்",
      ),
      drill(
        "bn-aramandi",
        "Aramandi (Half-Sit)",
        "Hold the half-sitting position with turned-out thighs",
        1,
        90,
        undefined,
        "Demi-plié position. Knees over toes.",
        "அரைமண்டி",
      ),
      drill(
        "bn-adavu-natta",
        "Natta Adavu",
        "Series of 8 Natta movements with full body coordination",
        2,
        150,
        80,
        "Each adavu repeated 4x. Crisp transitions.",
      ),
      drill(
        "bn-adavu-visharu",
        "Visharu Adavu",
        "Jumping adavu sequences testing elevation and landing",
        3,
        180,
        88,
        "Land with control. Maintain turned-out position.",
      ),
      drill(
        "bn-jatiswaram",
        "Jatiswaram",
        "Nritta piece in Misra Chapu talam",
        3,
        240,
        76,
      ),
      drill(
        "bn-varnam",
        "Varnam Excerpts",
        "Principal piece combining Nritta and Abhinaya",
        4,
        360,
        72,
        "Transition smoothly between abstract and expressive sections.",
      ),
      drill(
        "bn-padam",
        "Padam / Javali",
        "Pure Abhinaya – convey rasa through face and gesture",
        4,
        300,
        60,
        "Mudras (hand gestures) must be crisp and held.",
      ),
      drill(
        "bn-tillana",
        "Tillana",
        "Concluding fast-paced nritta with intricate footwork",
        5,
        300,
        120,
        "Maximum energy. All Adavus in sequence.",
      ),
    ],
  },
  {
    id: "kathak",
    name: "Kathak",
    nameLocal: "कत्थक",
    parentDiscipline: "dance",
    icon: "Repeat",
    color: "#a78bfa",
    origin: "Uttar Pradesh, India",
    description:
      "North Indian classical dance known for its lightning-fast spins (chakkar), intricate footwork, and expressive storytelling.",
    rhythmBPM: 90,
    coachingStyle: "rhythmic and expressive",
    scoringWeights: { ...WEIGHTS.classical, timing: 0.3 },
    drills: [
      drill(
        "kt-tatkar",
        "Tatkar",
        "Foundation footwork in Teen Taal (16 beats)",
        1,
        120,
        90,
        "Stamp firmly. Each beat distinct.",
        "तत्कार",
      ),
      drill(
        "kt-tode",
        "Tode & Tukde",
        "Short compositional units testing rhythm and movement",
        2,
        150,
        100,
      ),
      drill(
        "kt-chakkar",
        "Chakkar (Spins)",
        "Sustained spot spins – 8, 16, 32 rotations",
        3,
        120,
        108,
        "Fix gaze point (drishti). Rise onto balls of feet.",
        "चक्कर",
      ),
      drill(
        "kt-chakkar-advanced",
        "Advanced Chakkar Series",
        "64+ spins with padhant (spoken rhythm)",
        4,
        180,
        120,
        "Each spin must be identical. Land on sam (beat 1).",
      ),
      drill(
        "kt-thumri",
        "Thumri Abhinaya",
        "Expressive piece in semi-classical style",
        3,
        240,
        70,
        "Face, eyes, and hands must carry the narrative.",
      ),
      drill(
        "kt-tarana",
        "Tarana",
        "Fast-tempo abstract piece in Drut Laya",
        4,
        200,
        160,
        "Every syllable of the bols must be visible in the body.",
      ),
      drill(
        "kt-jugalbandi",
        "Jugalbandi Solo",
        "Dialogue between feet and tabla (simulated)",
        5,
        300,
        140,
        "Improvise within taal structure.",
      ),
    ],
  },
  {
    id: "odissi",
    name: "Odissi",
    nameLocal: "ଓଡ଼ିଶୀ",
    parentDiscipline: "dance",
    icon: "Columns",
    color: "#fb923c",
    origin: "Odisha, India",
    description:
      "Temple dance tradition of Odisha. Distinguished by the tribhangi (three-part body bend) and chauka (square stance).",
    rhythmBPM: 68,
    coachingStyle: "sculptural and meditative",
    scoringWeights: { ...WEIGHTS.classical, balance: 0.15, stability: 0.1 },
    drills: [
      drill(
        "od-chauka",
        "Chauka (Square Stance)",
        "Hold the fundamental chauka position",
        1,
        90,
        undefined,
        "Feet wide, knees bent outward, spine erect.",
        "ଚଉକ",
      ),
      drill(
        "od-tribhangi",
        "Tribhangi",
        "The iconic three-body-bend position",
        2,
        120,
        undefined,
        "Head, torso, hip each tilt opposite directions.",
        "ତ୍ରିଭଙ୍ଗ",
      ),
      drill(
        "od-bhoomi-pranam",
        "Bhoomi Pranam",
        "Opening invocation sequence",
        1,
        120,
        60,
      ),
      drill(
        "od-pallavi",
        "Pallavi",
        "Lyrical piece showcasing grammar of movement",
        3,
        300,
        72,
        "Eyes follow the hasta (hand gestures).",
      ),
      drill(
        "od-abhinaya",
        "Abhinaya Piece",
        "Expressive storytelling from Gita Govinda",
        4,
        300,
        60,
        "Sancharis (elaborations) must be vivid and distinct.",
      ),
      drill(
        "od-moksha",
        "Moksha",
        "Concluding piece – liberation through movement",
        5,
        300,
        96,
        "Build from stillness to full expression.",
      ),
    ],
  },
  {
    id: "kuchipudi",
    name: "Kuchipudi",
    nameLocal: "కూచిపూడి",
    parentDiscipline: "dance",
    icon: "Wind",
    color: "#4ade80",
    origin: "Andhra Pradesh, India",
    description:
      "Dance-drama tradition from Andhra Pradesh combining dance, music, and acting.",
    rhythmBPM: 80,
    coachingStyle: "dramatic and precise",
    scoringWeights: WEIGHTS.classical,
    drills: [
      drill(
        "ku-jatiswaram",
        "Jatiswaram",
        "Nritta in Kuchipudi style",
        2,
        180,
        80,
      ),
      drill(
        "ku-tarangam",
        "Tarangam on Plate",
        "Dance on the rim of a brass plate",
        4,
        240,
        96,
        "Balance entire weight on plate edges.",
      ),
      drill("ku-shabdam", "Shabdam", "Abhinaya to devotional song", 3, 240, 72),
      drill(
        "ku-full-item",
        "Kuchipudi Item Number",
        "Complete performance piece",
        5,
        360,
        90,
      ),
    ],
  },
  {
    id: "manipuri",
    name: "Manipuri",
    nameLocal: "মণিপুরী",
    parentDiscipline: "dance",
    icon: "Flower",
    color: "#f472b6",
    origin: "Manipur, India",
    description:
      "Lyrical and devotional classical dance from Manipur. Soft flowing movements, no sharp edges.",
    rhythmBPM: 64,
    coachingStyle: "gentle and devotional",
    scoringWeights: { ...WEIGHTS.classical, expressiveness: 0.3, power: 0.02 },
    drills: [
      drill(
        "mp-cholom",
        "Cholom (Drum Dance)",
        "Energetic male form with cymbals",
        3,
        180,
        100,
      ),
      drill(
        "mp-ras-lila",
        "Ras Lila Excerpts",
        "Devotional circular dance of Krishna-Radha",
        2,
        240,
        64,
        "Hands and eyes must suggest Bhakti (devotion).",
      ),
      drill(
        "mp-jagoi",
        "Jagoi",
        "Classical feminine form, flowing and soft",
        2,
        200,
        68,
      ),
      drill(
        "mp-full",
        "Full Ras Performance",
        "Complete devotional presentation",
        5,
        400,
        64,
      ),
    ],
  },
  {
    id: "mohiniyattam",
    name: "Mohiniyattam",
    nameLocal: "മോഹിനിയാട്ടം",
    parentDiscipline: "dance",
    icon: "Waves",
    color: "#22d3ee",
    origin: "Kerala, India",
    description:
      "Dance of the enchantress – Kerala classical form with wave-like swaying motion (lasya).",
    rhythmBPM: 60,
    coachingStyle: "flowing and sensuous",
    scoringWeights: {
      ...WEIGHTS.classical,
      expressiveness: 0.28,
      timing: 0.22,
    },
    drills: [
      drill(
        "mh-cholkettu",
        "Cholkettu",
        "Opening invocation piece",
        1,
        150,
        60,
      ),
      drill(
        "mh-jatiswaram",
        "Jatiswaram",
        "Abstract nritta in Mohiniyattam style",
        2,
        180,
        72,
      ),
      drill(
        "mh-padam",
        "Padam Abhinaya",
        "Expressive love poem",
        4,
        300,
        56,
        "Wave-like spinal movement throughout.",
      ),
      drill("mh-tillana", "Tillana", "Concluding nritta", 5, 240, 120),
    ],
  },
  {
    id: "sattriya",
    name: "Sattriya",
    nameLocal: "সত্ৰীয়া",
    parentDiscipline: "dance",
    icon: "User",
    color: "#fcd34d",
    origin: "Assam, India",
    description:
      "Monastic dance tradition from Vaishnavite monasteries of Assam.",
    rhythmBPM: 76,
    coachingStyle: "devotional and precise",
    scoringWeights: WEIGHTS.classical,
    drills: [
      drill(
        "st-vrindavani",
        "Vrindavani Satriya",
        "Invocatory piece",
        2,
        180,
        76,
      ),
      drill(
        "st-sutradhari",
        "Sutradhari Dance",
        "Narrator role in dance-drama",
        3,
        240,
        80,
      ),
      drill(
        "st-ankia-naat",
        "Ankia Naat Excerpt",
        "Dance-drama from Vaishnava plays",
        4,
        300,
        72,
      ),
    ],
  },
  // ── Indian Folk ──────────────────────────────────────────────────────────
  {
    id: "bhangra",
    name: "Bhangra",
    nameLocal: "ਭੰਗੜਾ",
    parentDiscipline: "dance",
    icon: "Music",
    color: "#f97316",
    origin: "Punjab, India/Pakistan",
    description:
      "High-energy Punjabi folk dance originally performed at harvest festivals.",
    rhythmBPM: 130,
    coachingStyle: "energetic and celebratory",
    scoringWeights: {
      ...WEIGHTS.dance,
      timing: 0.35,
      expressiveness: 0.2,
      power: 0.1,
    },
    drills: [
      drill(
        "bh-basic",
        "Basic Bhangra Step",
        "Side step with shoulder bounce",
        1,
        120,
        120,
      ),
      drill(
        "bh-gatka",
        "Gatka Movement",
        "Stick-twirling footwork sequence",
        2,
        150,
        130,
      ),
      drill(
        "bh-jumps",
        "High Jumps & Spins",
        "Explosive jumps with landing control",
        3,
        180,
        140,
      ),
      drill(
        "bh-full",
        "Full Bhangra Set",
        "Complete 4-minute performance",
        5,
        240,
        128,
      ),
    ],
  },
  {
    id: "garba",
    name: "Garba",
    nameLocal: "ગરબા",
    parentDiscipline: "dance",
    icon: "🔆",
    color: "#f43f5e",
    origin: "Gujarat, India",
    description:
      "Circular devotional folk dance from Gujarat performed during Navratri.",
    rhythmBPM: 100,
    coachingStyle: "joyful and rhythmic",
    scoringWeights: { ...WEIGHTS.dance, timing: 0.35 },
    drills: [
      drill(
        "ga-basic-circle",
        "Basic Circle Step",
        "3-step clap sequence in circle",
        1,
        120,
        100,
      ),
      drill(
        "ga-trikonee",
        "Trikonee (Triangle)",
        "Triangle pattern footwork",
        2,
        150,
        110,
      ),
      drill("ga-dodhiyu", "Dodhiyu Style", "2-beat Garba pattern", 3, 180, 100),
      drill(
        "ga-full",
        "Navratri Set",
        "Full Garba performance with variations",
        5,
        300,
        110,
      ),
    ],
  },
  {
    id: "lavani",
    name: "Lavani",
    nameLocal: "लावणी",
    parentDiscipline: "dance",
    icon: "💫",
    color: "#ec4899",
    origin: "Maharashtra, India",
    description:
      "Maharashtra folk performance combining sensuous dance with powerful rhythm.",
    rhythmBPM: 120,
    coachingStyle: "bold and rhythmic",
    scoringWeights: { ...WEIGHTS.dance, expressiveness: 0.25 },
    drills: [
      drill(
        "lv-basic",
        "Basic Lavani Step",
        "Hip and shoulder coordination",
        2,
        150,
        120,
      ),
      drill(
        "lv-mujra",
        "Mujra-style Footwork",
        "Traditional kotha footwork",
        3,
        180,
        130,
      ),
      drill(
        "lv-full",
        "Full Lavani Performance",
        "Complete lavani with abhinaya",
        5,
        300,
        120,
      ),
    ],
  },
  {
    id: "dandiya",
    name: "Dandiya Raas",
    nameLocal: "ડાંડિયા",
    parentDiscipline: "dance",
    icon: "🎋",
    color: "#fbbf24",
    origin: "Gujarat, India",
    description: "Stick dance of Gujarat performed in pairs during Navratri.",
    rhythmBPM: 116,
    coachingStyle: "energetic and coordinated",
    scoringWeights: { ...WEIGHTS.dance, timing: 0.38 },
    drills: [
      drill(
        "da-basic",
        "Basic Strike Pattern",
        "8-count stick-clap sequence",
        1,
        120,
        116,
      ),
      drill(
        "da-turns",
        "Turn Patterns",
        "Pivot and strike combinations",
        3,
        180,
        120,
      ),
      drill(
        "da-full",
        "Full Dandiya Set",
        "Complete raas with 6 variations",
        5,
        240,
        116,
      ),
    ],
  },
  // ── Western / Urban ────────────────────────────────────────────────────────
  {
    id: "ballet",
    name: "Ballet",
    nameLocal: "Ballet",
    parentDiscipline: "dance",
    icon: "Activity",
    color: "#f9a8d4",
    origin: "France/Italy",
    description:
      "Classical Western dance technique emphasising turnout, extensions, and pointe work.",
    rhythmBPM: 72,
    coachingStyle: "precise and classical",
    scoringWeights: {
      accuracy: 0.35,
      stability: 0.15,
      timing: 0.2,
      expressiveness: 0.15,
      power: 0.05,
      balance: 0.1,
    },
    drills: [
      drill(
        "ba-plie",
        "Pliés at Barre",
        "1st, 2nd, 4th, 5th position pliés",
        1,
        120,
        56,
      ),
      drill(
        "ba-tendu",
        "Tendus & Dégagés",
        "Battement tendu in all directions",
        2,
        150,
        60,
      ),
      drill(
        "ba-adage",
        "Centre Adage",
        "Slow centre-floor lyrical combination",
        3,
        180,
        52,
        "Line through fingertips.",
      ),
      drill(
        "ba-pirouette",
        "Pirouettes",
        "Single and double en dehors/dedans",
        4,
        120,
        96,
      ),
      drill(
        "ba-grand-allegro",
        "Grand Allegro",
        "Big jumps and turns combination",
        5,
        180,
        100,
      ),
    ],
  },
  {
    id: "hiphop",
    name: "Hip-Hop",
    parentDiscipline: "dance",
    icon: "🎤",
    color: "#64748b",
    origin: "New York, USA",
    description:
      "Street dance culture rooted in the Bronx. Grooves, isolations, and freestyle.",
    rhythmBPM: 90,
    coachingStyle: "street and expressive",
    scoringWeights: { ...WEIGHTS.dance, timing: 0.35, expressiveness: 0.25 },
    drills: [
      drill(
        "hh-bounce",
        "Bounce & Groove",
        "Find your groove – internal bounce",
        1,
        120,
        90,
      ),
      drill(
        "hh-isolations",
        "Body Isolations",
        "Head, chest, hip isolations",
        2,
        150,
        88,
      ),
      drill(
        "hh-cypher",
        "Cypher 8-count",
        "8-count freestyle sequence",
        3,
        180,
        92,
        "Stay in your lane. Express authentically.",
      ),
      drill(
        "hh-commercial",
        "Commercial Choreo",
        "Sync choreography to 32-count",
        4,
        240,
        96,
      ),
      drill(
        "hh-freestyle",
        "Freestyle Battle Round",
        "1-min freestyle to unknown track",
        5,
        60,
        undefined,
        "No prep. Pure expression.",
      ),
    ],
  },
  {
    id: "breakdance",
    name: "Breakdance (B-Boying)",
    parentDiscipline: "dance",
    icon: "💥",
    color: "#ef4444",
    origin: "Bronx, New York",
    description: "Four elements: Toprock, Footwork, Freezes, Power moves.",
    rhythmBPM: 110,
    coachingStyle: "explosive and creative",
    scoringWeights: {
      accuracy: 0.2,
      stability: 0.2,
      timing: 0.2,
      expressiveness: 0.2,
      power: 0.15,
      balance: 0.05,
    },
    drills: [
      drill(
        "bb-toprock",
        "Toprock",
        "Standing entry step sequence",
        1,
        90,
        110,
      ),
      drill(
        "bb-6step",
        "6-Step Footwork",
        "Foundation floor work",
        2,
        120,
        108,
      ),
      drill(
        "bb-freeze",
        "Baby Freeze",
        "Entry level freeze hold",
        2,
        60,
        undefined,
        "Lock arms. Hold 3 full seconds.",
      ),
      drill(
        "bb-headspin",
        "Windmill-to-Freeze",
        "Power move into freeze",
        4,
        120,
        undefined,
      ),
      drill("bb-battle", "Battle Round", "1v1 battle simulation", 5, 90, 110),
    ],
  },
  {
    id: "salsa",
    name: "Salsa",
    parentDiscipline: "dance",
    icon: "Flame",
    color: "#dc2626",
    origin: "Caribbean/New York",
    description: "Latin partner dance on 1 or 2 timing. Lead/follow dynamic.",
    rhythmBPM: 180,
    coachingStyle: "passionate and rhythmic",
    scoringWeights: { ...WEIGHTS.dance, timing: 0.38 },
    drills: [
      drill(
        "sa-basic",
        "Basic Step On1",
        "Forward-back basic on beat 1",
        1,
        120,
        180,
      ),
      drill(
        "sa-cross-body",
        "Cross-Body Lead",
        "Classic cross-body turn pattern",
        2,
        150,
        180,
      ),
      drill(
        "sa-shines",
        "Footwork Shines",
        "Solo footwork showcase",
        3,
        180,
        180,
      ),
      drill(
        "sa-turn-patterns",
        "Advanced Turn Patterns",
        "Multiple turns in sequence",
        4,
        240,
        180,
      ),
      drill(
        "sa-improvise",
        "Improvisation Round",
        "Full improvisation to unknown salsa track",
        5,
        120,
        180,
      ),
    ],
  },
  {
    id: "tango",
    name: "Tango",
    parentDiscipline: "dance",
    icon: "Heart",
    color: "#7f1d1d",
    origin: "Buenos Aires, Argentina",
    description:
      "Argentine tango – improvised partner dance of walking, pausing, and embellishments.",
    rhythmBPM: 130,
    coachingStyle: "precise and passionate",
    scoringWeights: {
      accuracy: 0.3,
      stability: 0.2,
      timing: 0.2,
      expressiveness: 0.2,
      power: 0.05,
      balance: 0.05,
    },
    drills: [
      drill(
        "ta-walk",
        "Tango Walk",
        "The fundamental tango walk forward/back",
        1,
        120,
        130,
      ),
      drill("ta-ocho", "Ochos", "Forward and back ochos", 2, 150, 130),
      drill(
        "ta-giro",
        "Giro (Turn)",
        "Full circular turn pattern",
        3,
        180,
        128,
      ),
      drill(
        "ta-volcada",
        "Volcada & Colgada",
        "Off-axis shared weight movements",
        5,
        200,
        126,
      ),
    ],
  },
  {
    id: "flamenco",
    name: "Flamenco",
    parentDiscipline: "dance",
    icon: "🌺",
    color: "#b91c1c",
    origin: "Andalusia, Spain",
    description:
      "Spanish art form combining footwork (zapateado), arm work (braceo), and song.",
    rhythmBPM: 140,
    coachingStyle: "passionate and dramatic",
    scoringWeights: {
      accuracy: 0.25,
      stability: 0.15,
      timing: 0.3,
      expressiveness: 0.2,
      power: 0.05,
      balance: 0.05,
    },
    drills: [
      drill(
        "fl-zapateado",
        "Zapateado Basic",
        "Rhythmic footwork in Bulería compás",
        2,
        120,
        140,
      ),
      drill(
        "fl-braceo",
        "Braceo (Arm Work)",
        "Slow serpentine arm movement",
        1,
        90,
        undefined,
      ),
      drill(
        "fl-soleares",
        "Soleares Sequence",
        "12-beat Soleares palo structure",
        3,
        240,
        100,
        "Listen for the 12-beat compás cycle.",
      ),
      drill(
        "fl-full",
        "Full Solo Farruca",
        "Complete traditional Farruca",
        5,
        360,
        112,
      ),
    ],
  },
  {
    id: "kpop",
    name: "K-Pop",
    parentDiscipline: "dance",
    icon: "💜",
    color: "#a855f7",
    origin: "South Korea",
    description:
      "Synchronised, precision group choreography style from Korean pop music.",
    rhythmBPM: 128,
    coachingStyle: "sharp and synchronised",
    scoringWeights: { ...WEIGHTS.dance, accuracy: 0.35, timing: 0.35 },
    drills: [
      drill("kp-wave", "Body Wave", "Signature K-pop wave motion", 1, 90, 128),
      drill(
        "kp-point",
        "Point Choreo",
        "Iconic point move sequences",
        2,
        120,
        130,
      ),
      drill(
        "kp-sync",
        "Sync Challenge",
        "16-count precision sync drill",
        3,
        180,
        128,
      ),
      drill(
        "kp-full",
        "Full Comeback Choreo",
        "Complete 3-minute performance",
        5,
        180,
        128,
      ),
    ],
  },
  {
    id: "belly_dance",
    name: "Belly Dance",
    nameLocal: "رقص شرقي",
    parentDiscipline: "dance",
    icon: "✨",
    color: "#d97706",
    origin: "Middle East/North Africa",
    description:
      "Oriental dance emphasising isolations of the torso, hips, and arms.",
    rhythmBPM: 96,
    coachingStyle: "expressive and flowing",
    scoringWeights: {
      accuracy: 0.25,
      stability: 0.15,
      timing: 0.25,
      expressiveness: 0.25,
      power: 0.05,
      balance: 0.05,
    },
    drills: [
      drill(
        "bd-hip-circle",
        "Hip Circle",
        "Full horizontal hip circle",
        1,
        90,
        96,
      ),
      drill(
        "bd-shimmy",
        "Shimmy",
        "Fast hip shimmy sustained 30sec",
        2,
        120,
        120,
      ),
      drill(
        "bd-snake-arms",
        "Snake Arms",
        "Alternating wave through arms",
        1,
        90,
        80,
      ),
      drill(
        "bd-full",
        "Drum Solo",
        "Full drum solo improvisation",
        5,
        180,
        120,
      ),
    ],
  },
  {
    id: "afrobeats",
    name: "Afrobeats",
    parentDiscipline: "dance",
    icon: "Music",
    color: "#84cc16",
    origin: "West Africa",
    description: "African-rooted rhythmic dance to Afrobeats music.",
    rhythmBPM: 115,
    coachingStyle: "grounded and rhythmic",
    scoringWeights: { ...WEIGHTS.dance, timing: 0.35 },
    drills: [
      drill(
        "af-shaku",
        "Shaku Shaku",
        "Nigerian street dance step",
        1,
        90,
        115,
      ),
      drill(
        "af-zanku",
        "Zanku (Leg Work)",
        "Leg-work heavy sequence",
        2,
        120,
        115,
      ),
      drill(
        "af-full",
        "Full Afrobeats Set",
        "3-minute freestyle performance",
        5,
        180,
        115,
      ),
    ],
  },
  {
    id: "freestyle",
    name: "Freestyle",
    parentDiscipline: "dance",
    icon: "Waves",
    color: "#06b6d4",
    origin: "Global",
    description:
      "No style constraints. Express your authentic movement vocabulary.",
    rhythmBPM: 100,
    coachingStyle: "open and creative",
    scoringWeights: {
      accuracy: 0.15,
      stability: 0.15,
      timing: 0.25,
      expressiveness: 0.3,
      power: 0.1,
      balance: 0.05,
    },
    drills: [
      drill(
        "fr-warmup",
        "Freestyle Warmup",
        "Move freely for 2 minutes",
        1,
        120,
        undefined,
        "No rules. Just move.",
      ),
      drill(
        "fr-one-song",
        "One Song Freestyle",
        "Full freestyle to one track",
        3,
        200,
        undefined,
      ),
      drill(
        "fr-challenge",
        "Trend Challenge",
        "Create and execute a 15-second signature move",
        5,
        60,
        undefined,
      ),
    ],
  },
];

// ─── MARTIAL ARTS SUB-DISCIPLINES ──────────────────────────────────────────────

export const MARTIAL_ARTS_SUB_DISCIPLINES: SubDiscipline[] = [
  {
    id: "karate_shotokan",
    name: "Karate – Shotokan",
    nameLocal: "空手道 松涛館",
    parentDiscipline: "martialarts",
    icon: "Zap",
    color: "#dc2626",
    origin: "Okinawa / Japan",
    description:
      "Linear, powerful karate style. Strong stances, deep blocks, explosive strikes.",
    rhythmBPM: 80,
    coachingStyle: "disciplined and precise",
    scoringWeights: WEIGHTS.martial,
    drills: [
      drill(
        "ks-kihon",
        "Kihon (Basics)",
        "Gyaku-zuki in front stance – 20 reps",
        1,
        120,
        80,
      ),
      drill(
        "ks-heian-shodan",
        "Heian Shodan Kata",
        "First Heian kata – 21 movements",
        2,
        150,
        80,
      ),
      drill(
        "ks-heian-godan",
        "Heian Godan Kata",
        "Fifth Heian kata with jump",
        3,
        180,
        80,
      ),
      drill(
        "ks-bassai-dai",
        "Bassai Dai Kata",
        "Advanced kata with power strikes",
        4,
        200,
        80,
      ),
      drill(
        "ks-kanku-dai",
        "Kanku Dai Kata",
        "Master kata – full performance",
        5,
        300,
        80,
      ),
    ],
  },
  {
    id: "karate_kyokushin",
    name: "Karate – Kyokushin",
    nameLocal: "極真空手",
    parentDiscipline: "martialarts",
    icon: "Frown",
    color: "#b91c1c",
    origin: "Japan",
    description:
      "Full-contact karate emphasising devastating body kicks and iron conditioning.",
    rhythmBPM: 100,
    coachingStyle: "brutal and conditioning-focused",
    scoringWeights: { ...WEIGHTS.martial, power: 0.2, accuracy: 0.3 },
    drills: [
      drill(
        "kk-100kicks",
        "100 Kick Drill",
        "Mawashi-geri (roundhouse) x100",
        3,
        300,
        undefined,
        "Pivot on standing foot. Pull hip through.",
      ),
      drill(
        "kk-tameshiwari",
        "Tameshiwari Form",
        "Breaking power technique simulation",
        4,
        120,
        undefined,
      ),
      drill(
        "kk-ibuki",
        "Ibuki Breathing Kata",
        "Sanchin kata with full ibuki breathing",
        2,
        180,
        undefined,
      ),
      drill(
        "kk-tournament",
        "Tournament Kumite Round",
        "2-min full-contact simulation",
        5,
        120,
        100,
      ),
    ],
  },
  {
    id: "taekwondo_wtf",
    name: "Taekwondo – WTF",
    nameLocal: "태권도",
    parentDiscipline: "martialarts",
    icon: "🦵",
    color: "#3b82f6",
    origin: "South Korea",
    description:
      "Olympic Taekwondo. Lightning-fast head kicks, footwork, and Olympic-style scoring.",
    rhythmBPM: 120,
    coachingStyle: "explosive and technical",
    scoringWeights: { ...WEIGHTS.martial, timing: 0.25, power: 0.15 },
    drills: [
      drill(
        "tkd-ap-chagi",
        "Ap Chagi (Front Kick)",
        "20 reps each leg – full extension",
        1,
        90,
        undefined,
      ),
      drill(
        "tkd-dollyo-chagi",
        "Dollyo Chagi (Roundhouse)",
        "High section roundhouse drill",
        2,
        120,
        undefined,
      ),
      drill(
        "tkd-twi-miro",
        "Jumping Spin Kick",
        "Tornado kick sequence",
        4,
        120,
        undefined,
        "Generate rotation from hip, not shoulder.",
      ),
      drill(
        "tkd-poomsae",
        "Taegeuk Poomsae",
        "Olympic poomsae sequence",
        3,
        180,
        80,
      ),
      drill(
        "tkd-sparring",
        "Olympic Sparring Simulation",
        "2x1min rounds",
        5,
        120,
        120,
      ),
    ],
  },
  {
    id: "muay_thai",
    name: "Muay Thai",
    nameLocal: "มวยไทย",
    parentDiscipline: "martialarts",
    icon: "🦾",
    color: "#ef4444",
    origin: "Thailand",
    description:
      "Art of 8 limbs. Punches, kicks, elbows, knees with clinch work.",
    rhythmBPM: 90,
    coachingStyle: "fierce and technical",
    scoringWeights: { ...WEIGHTS.boxing, power: 0.2 },
    drills: [
      drill(
        "mt-wai-kru",
        "Wai Kru Ram Muay",
        "Traditional pre-fight ritual dance",
        1,
        180,
        56,
      ),
      drill(
        "mt-teep",
        "Teep (Push Kick)",
        "Front push kick with hip extension",
        1,
        90,
        undefined,
      ),
      drill(
        "mt-roundhouse",
        "Low-High Roundhouse",
        "Shin kick targeting legs then head",
        2,
        120,
        undefined,
      ),
      drill(
        "mt-elbow-combo",
        "Elbow Combo",
        "Horizontal + diagonal elbow series",
        3,
        120,
        undefined,
        "Drive from shoulder, not arm.",
      ),
      drill(
        "mt-clinch",
        "Clinch Drill",
        "Knee strikes in clinch position",
        3,
        120,
        undefined,
      ),
      drill(
        "mt-5round",
        "5-Combo Round",
        "Full 2-minute Muay Thai round",
        5,
        120,
        90,
      ),
    ],
  },
  {
    id: "kung_fu_shaolin",
    name: "Shaolin Kung Fu",
    nameLocal: "少林功夫",
    parentDiscipline: "martialarts",
    icon: "🏯",
    color: "#f97316",
    origin: "Henan, China",
    description:
      "Temple boxing from Shaolin. Animal forms, iron training, and acrobatic strikes.",
    rhythmBPM: 80,
    coachingStyle: "spiritual and explosive",
    scoringWeights: WEIGHTS.martial,
    drills: [
      drill(
        "sf-horse",
        "Horse Stance Conditioning",
        "Ma bu hold – 3 minutes target",
        2,
        180,
        undefined,
        "Thighs parallel to ground. Back flat.",
        "馬步",
      ),
      drill(
        "sf-five-animals",
        "Five Animal Form",
        "Tiger, Crane, Dragon, Leopard, Snake sequence",
        3,
        300,
        72,
      ),
      drill(
        "sf-iron-palm",
        "Iron Palm Conditioning",
        "Palm strike training sequence",
        3,
        120,
        undefined,
      ),
      drill(
        "sf-lian-huan",
        "Lian Huan Quan",
        "Continuous fist form",
        4,
        240,
        88,
      ),
      drill(
        "sf-wushu-routine",
        "Changquan Routine",
        "Competition Wushu long fist",
        5,
        300,
        100,
      ),
    ],
  },
  {
    id: "kung_fu_wing_chun",
    name: "Wing Chun",
    nameLocal: "詠春",
    parentDiscipline: "martialarts",
    icon: "🖐️",
    color: "#fcd34d",
    origin: "Guangdong, China",
    description:
      "Close-range system relying on sensitivity, chain punches, and centerline theory.",
    rhythmBPM: 80,
    coachingStyle: "sensitive and technical",
    scoringWeights: { ...WEIGHTS.martial, stability: 0.25, accuracy: 0.35 },
    drills: [
      drill(
        "wc-siu-nim-tao",
        "Siu Nim Tao Form",
        "First form – slow and precise",
        2,
        300,
        undefined,
        "No tension. Form must be completely relaxed.",
        "小念頭",
      ),
      drill(
        "wc-chain-punch",
        "Chain Punch Drill",
        "Centerline chain punches x50",
        2,
        60,
        undefined,
      ),
      drill(
        "wc-chum-kiu",
        "Chum Kiu Form",
        "Second form – turning and kicking",
        3,
        300,
        undefined,
        "橋中求",
      ),
      drill(
        "wc-chi-sao",
        "Chi Sao (Sticky Hands)",
        "Solo chi sao rolling patterns",
        4,
        180,
        undefined,
      ),
      drill(
        "wc-wooden-dummy",
        "Wooden Dummy Form",
        "Muk Yan Jong 116-movement form",
        5,
        420,
        undefined,
        "木人樁法",
      ),
    ],
  },
  {
    id: "kung_fu_tai_chi",
    name: "Tai Chi",
    nameLocal: "太極拳",
    parentDiscipline: "martialarts",
    icon: "☯️",
    color: "#6ee7b7",
    origin: "China",
    description:
      "Internal martial art practised for health and meditation. Slow flowing movements.",
    rhythmBPM: 40,
    coachingStyle: "meditative and flowing",
    scoringWeights: {
      accuracy: 0.25,
      stability: 0.15,
      timing: 0.2,
      expressiveness: 0.15,
      power: 0.05,
      balance: 0.2,
    },
    drills: [
      drill(
        "tc-wave-hands",
        "Wave Hands Like Clouds",
        "Slow lateral weight shift with arm circles",
        1,
        180,
        40,
      ),
      drill(
        "tc-brush-knee",
        "Brush Knee and Twist Step",
        "Classic Yang-style posture sequence",
        2,
        200,
        38,
      ),
      drill(
        "tc-24form",
        "24-Form Yang Style",
        "Standard simplified 24-movement form",
        3,
        480,
        36,
      ),
      drill(
        "tc-108form",
        "Traditional 108-Form",
        "Full Yang family long form",
        5,
        1200,
        34,
      ),
    ],
  },
  {
    id: "capoeira",
    name: "Capoeira",
    parentDiscipline: "martialarts",
    icon: "🎵",
    color: "#f59e0b",
    origin: "Brazil",
    description:
      "Afro-Brazilian martial art combining acrobatics, music, and dance in a game called jogo.",
    rhythmBPM: 120,
    coachingStyle: "creative and playful",
    scoringWeights: {
      accuracy: 0.2,
      stability: 0.15,
      timing: 0.25,
      expressiveness: 0.2,
      power: 0.1,
      balance: 0.1,
    },
    drills: [
      drill(
        "cp-ginga",
        "Ginga",
        "Foundation swaying movement",
        1,
        120,
        80,
        "Never stop moving. The ginga is constant.",
      ),
      drill("cp-au", "Aú (Cartwheel)", "Basic Capoeira cartwheel", 2, 90, 100),
      drill(
        "cp-galpao",
        "Au Batido Sequence",
        "Cartwheel + kick combination",
        3,
        150,
        110,
      ),
      drill(
        "cp-meia-lua",
        "Meia Lua de Compasso",
        "Spinning heel kick",
        4,
        120,
        120,
      ),
      drill("cp-jogo", "Jogo Round", "2-minute game simulation", 5, 120, 120),
    ],
  },
  {
    id: "judo",
    name: "Judo",
    nameLocal: "柔道",
    parentDiscipline: "martialarts",
    icon: "Zap",
    color: "#1d4ed8",
    origin: "Japan",
    description:
      "Throws, sweeps, and ground control. Kuzushi (unbalancing), Tsukuri (fitting in), Kake (execution).",
    rhythmBPM: undefined,
    coachingStyle: "technical and methodical",
    scoringWeights: {
      accuracy: 0.35,
      stability: 0.25,
      timing: 0.2,
      expressiveness: 0.05,
      power: 0.1,
      balance: 0.05,
    },
    drills: [
      drill(
        "ju-ukemi",
        "Ukemi (Breakfall)",
        "Forward, backward, sideways breakfalls",
        1,
        120,
        undefined,
      ),
      drill(
        "ju-throws",
        "O-Goshi & Seoi-nage",
        "Hip throw and shoulder throw entries",
        2,
        150,
        undefined,
        "Focus on kuzushi before throw.",
      ),
      drill(
        "ju-ne-waza",
        "Ne-waza (Ground Work)",
        "Kesa gatame and osae komi",
        3,
        180,
        undefined,
      ),
      drill(
        "ju-combination",
        "Attack-Counter Combination",
        "Ko-uchi to seoi-nage to armbar",
        4,
        180,
        undefined,
      ),
      drill(
        "ju-randori",
        "Randori Simulation",
        "3-minute practice match",
        5,
        180,
        undefined,
      ),
    ],
  },
  {
    id: "kalaripayattu",
    name: "Kalaripayattu",
    nameLocal: "കളരിപ്പയറ്റ്",
    parentDiscipline: "martialarts",
    icon: "🗡️",
    color: "#b45309",
    origin: "Kerala, India",
    description:
      "One of the world's oldest martial arts. Animal postures, weapons, and healing.",
    rhythmBPM: 80,
    coachingStyle: "ancient and disciplined",
    scoringWeights: { ...WEIGHTS.martial, expressiveness: 0.15 },
    drills: [
      drill(
        "kp-meipayat",
        "Meipayat",
        "Body conditioning sequence – flexibility and strength",
        2,
        180,
        undefined,
        "Oil body before training for maximum flexibility.",
        "മെയ്‌പ്പയറ്റ്",
      ),
      drill(
        "kp-horse-form",
        "Ashwavadivu (Horse Stance)",
        "Low horse stance held 3 minutes",
        2,
        180,
        undefined,
      ),
      drill(
        "kp-lion-form",
        "Simhavadivu (Lion Form)",
        "Attacking lion posture sequence",
        3,
        200,
        88,
      ),
      drill(
        "kp-stick",
        "Kettukari (Long Stick)",
        "Stick combat sequence",
        4,
        240,
        80,
      ),
      drill(
        "kp-urumi",
        "Urumi (Flexible Sword)",
        "Serpentine flexible sword form",
        5,
        300,
        76,
        "The urumi can cut the user — maximum control required.",
        "ഉറുമി",
      ),
    ],
  },
  {
    id: "mma",
    name: "MMA",
    parentDiscipline: "martialarts",
    icon: "🔺",
    color: "#6b7280",
    origin: "Global",
    description:
      "Mixed Martial Arts – combining striking, wrestling, and ground work.",
    rhythmBPM: 100,
    coachingStyle: "analytical and aggressive",
    scoringWeights: {
      accuracy: 0.25,
      stability: 0.2,
      timing: 0.25,
      expressiveness: 0.05,
      power: 0.2,
      balance: 0.05,
    },
    drills: [
      drill(
        "mma-striking",
        "Striking Combination",
        "Jab-cross-low kick-high kick",
        2,
        120,
        100,
      ),
      drill(
        "mma-wrestling",
        "Double-Leg Takedown",
        "Level change and shot sequence",
        3,
        90,
        undefined,
      ),
      drill(
        "mma-ground-pound",
        "Ground & Pound",
        "Mounted striking with control",
        3,
        90,
        undefined,
      ),
      drill(
        "mma-scramble",
        "Scramble Drill",
        "Stand-up to ground transitions",
        4,
        180,
        undefined,
      ),
      drill(
        "mma-full-round",
        "5-Minute Round",
        "Full MMA round simulation",
        5,
        300,
        100,
      ),
    ],
  },
];

// ─── BOXING SUB-DISCIPLINES ────────────────────────────────────────────────────

export const BOXING_SUB_DISCIPLINES: SubDiscipline[] = [
  {
    id: "orthodox",
    name: "Orthodox Boxing",
    parentDiscipline: "boxing",
    icon: "Swords",
    color: "#ff6b35",
    origin: "Global",
    description:
      "Standard stance with left jab leading. Emphasis on jab-cross combinations.",
    rhythmBPM: 80,
    coachingStyle: "aggressive",
    scoringWeights: WEIGHTS.boxing,
    drills: [
      drill(
        "bx-jab",
        "Jab Drill",
        "100 jabs – speed and accuracy",
        1,
        90,
        undefined,
        "Snap back immediately. No telegraphing.",
      ),
      drill(
        "bx-1-2",
        "Jab-Cross (1-2)",
        "50 combinations at full speed",
        1,
        90,
        undefined,
      ),
      drill(
        "bx-1-2-3",
        "Jab-Cross-Hook (1-2-3)",
        "Three-punch combination",
        2,
        120,
        undefined,
      ),
      drill(
        "bx-body-work",
        "Body Shot Combos",
        "Liver and solar plexus targeting",
        3,
        120,
        undefined,
      ),
      drill(
        "bx-defense",
        "Slip & Counter",
        "Slip the jab, counter with right",
        3,
        150,
        undefined,
        "Move head offline before punching.",
      ),
      drill(
        "bx-mitt-work",
        "Mitt Work Simulation",
        "Following coach call sequences",
        4,
        180,
        80,
      ),
      drill(
        "bx-full-round",
        "Full Round (3 min)",
        "Complete boxing round",
        5,
        180,
        80,
      ),
    ],
  },
  {
    id: "southpaw",
    name: "Southpaw Boxing",
    parentDiscipline: "boxing",
    icon: "Swords",
    color: "#f97316",
    origin: "Global",
    description: "Left-hand dominant stance. Right jab leads from right side.",
    rhythmBPM: 80,
    coachingStyle: "aggressive",
    scoringWeights: WEIGHTS.boxing,
    drills: [
      drill(
        "sp-right-jab",
        "Right Jab Drill",
        "Southpaw right jab – speed work",
        1,
        90,
        undefined,
      ),
      drill(
        "sp-2-1",
        "Right Jab – Left Cross",
        "Southpaw mirror combination",
        1,
        90,
        undefined,
      ),
      drill(
        "sp-check-hook",
        "Check Hook vs Orthodox",
        "Counter for orthodox charging fighters",
        3,
        150,
        undefined,
      ),
      drill(
        "sp-full",
        "Southpaw Sparring Round",
        "Angle work vs. orthodox stance",
        5,
        180,
        80,
      ),
    ],
  },
  {
    id: "kickboxing_k1",
    name: "Kickboxing – K1 Rules",
    parentDiscipline: "boxing",
    icon: "Zap",
    color: "#fbbf24",
    origin: "Japan/Global",
    description: "Punches and kicks above the waist. K-1 Grand Prix rules.",
    rhythmBPM: 100,
    coachingStyle: "explosive and technical",
    scoringWeights: { ...WEIGHTS.boxing, accuracy: 0.28, power: 0.18 },
    drills: [
      drill(
        "k1-switch-kick",
        "Switch Kick",
        "Switch feet and fire rear leg kick",
        2,
        120,
        undefined,
      ),
      drill(
        "k1-body-kick",
        "Body Kick Combination",
        "Jab-cross-body kick",
        3,
        150,
        undefined,
      ),
      drill(
        "k1-spinning",
        "Spinning Back Kick",
        "Pivot and thrust rear kick",
        4,
        120,
        undefined,
      ),
      drill("k1-full", "K-1 Round", "3-minute K-1 rules round", 5, 180, 100),
    ],
  },
];

// ─── YOGA SUB-DISCIPLINES ──────────────────────────────────────────────────────

export const YOGA_SUB_DISCIPLINES: SubDiscipline[] = [
  {
    id: "hatha",
    name: "Hatha Yoga",
    nameLocal: "हठ योग",
    parentDiscipline: "yoga",
    icon: "🌞",
    color: "#fbbf24",
    origin: "India",
    description:
      "Classical system of poses and breathing. Foundation of all yoga styles.",
    rhythmBPM: 40,
    coachingStyle: "calm",
    scoringWeights: WEIGHTS.yoga,
    drills: [
      drill(
        "hy-sun-sal",
        "Surya Namaskar A",
        "5 rounds of Sun Salutation A",
        1,
        300,
        40,
        "Every transition on a breath.",
        "सूर्य नमस्कार",
      ),
      drill(
        "hy-warrior-1",
        "Virabhadrasana I",
        "Warrior I – 60sec each side",
        2,
        120,
        undefined,
        "Back heel grounded. Hips square forward.",
        "वीरभद्रासन",
      ),
      drill(
        "hy-tree",
        "Vrikshasana",
        "Tree pose – 90sec each side",
        2,
        180,
        undefined,
        "Soft gaze. Find drishti.",
        "वृक्षासन",
      ),
      drill(
        "hy-headstand",
        "Shirshasana (Headstand)",
        "Headstand hold up to 3 min",
        4,
        180,
        undefined,
        "Build from forearm balance first.",
        "शीर्षासन",
      ),
      drill(
        "hy-full",
        "Full Class Sequence",
        "45-minute Hatha class",
        5,
        2700,
        38,
      ),
    ],
  },
  {
    id: "ashtanga",
    name: "Ashtanga Yoga",
    nameLocal: "अष्टांग योग",
    parentDiscipline: "yoga",
    icon: "Flame",
    color: "#ef4444",
    origin: "Mysore, India",
    description:
      "Fixed sequential series with Vinyasa (breath-movement) and Bandha (energy locks).",
    rhythmBPM: 48,
    coachingStyle: "disciplined and internal",
    scoringWeights: { ...WEIGHTS.yoga, timing: 0.25, balance: 0.2 },
    drills: [
      drill(
        "as-surya-a",
        "Surya Namaskar A – 5 rounds",
        "Opening sequence",
        2,
        300,
        48,
      ),
      drill(
        "as-standing",
        "Standing Sequence",
        "Padangusthasana through Virabhadrasana",
        3,
        600,
        44,
      ),
      drill(
        "as-seated",
        "Seated Sequence Opening",
        "Dandasana through Triang Mukhaikapada",
        4,
        600,
        42,
      ),
      drill(
        "as-primary-full",
        "Full Primary Series",
        "Complete first series Ashtanga",
        5,
        5400,
        40,
      ),
    ],
  },
  {
    id: "kundalini",
    name: "Kundalini Yoga",
    nameLocal: "कुण्डलिनी योग",
    parentDiscipline: "yoga",
    icon: "🐍",
    color: "#8b5cf6",
    origin: "Punjab, India",
    description:
      "Kriya-based yoga activating kundalini energy through breathwork, chanting, and movement.",
    rhythmBPM: 60,
    coachingStyle: "spiritual and energetic",
    scoringWeights: { ...WEIGHTS.yoga, expressiveness: 0.2, timing: 0.2 },
    drills: [
      drill(
        "ku-sat-kriya",
        "Sat Kriya",
        "3-min continuous Sat Kriya with breath of fire",
        3,
        180,
        undefined,
        "Navel pulled in on Sat. Released on Nam.",
        "ਸਤਿ ਕ੍ਰਿਯਾ",
      ),
      drill(
        "ku-breath-fire",
        "Breath of Fire",
        "3 minutes Kapalabhati-style rapid breath",
        2,
        180,
        undefined,
        "2-3 breaths per second.",
        "अग्नि प्राणायाम",
      ),
      drill(
        "ku-archer",
        "Archer Pose Series",
        "Virabhava with gaze and mudra",
        2,
        300,
        undefined,
      ),
      drill(
        "ku-full-kriya",
        "Full Kriya Set",
        "11-minute morning kriya",
        4,
        660,
        48,
      ),
    ],
  },
  {
    id: "vinyasa",
    name: "Vinyasa Flow",
    parentDiscipline: "yoga",
    icon: "Waves",
    color: "#06b6d4",
    origin: "Global",
    description:
      "Creative flows linking breath to movement. Non-fixed sequences.",
    rhythmBPM: 52,
    coachingStyle: "flowing and creative",
    scoringWeights: { ...WEIGHTS.yoga, timing: 0.25 },
    drills: [
      drill(
        "vn-wave1",
        "Wave 1: Foundation",
        "Cat-cow to downdog to standing",
        1,
        240,
        52,
      ),
      drill(
        "vn-hip-flow",
        "Hip Opening Flow",
        "Lizard, pigeon, frog series",
        3,
        480,
        44,
      ),
      drill(
        "vn-inversion",
        "Inversion Flow",
        "Headstand – shoulderstand – plow",
        4,
        360,
        44,
      ),
      drill(
        "vn-full",
        "Creative Vinyasa Class",
        "60-min full creative flow",
        5,
        3600,
        48,
      ),
    ],
  },
];

// ─── MAIN DISCIPLINES ARRAY ────────────────────────────────────────────────────

export const DISCIPLINES: Discipline[] = [
  {
    id: "boxing",
    name: "Boxing",
    icon: "Swords",
    color: "#ff6b35",
    glow: "rgba(255,107,53,0.4)",
    bg: "rgba(255,107,53,0.08)",
    coachingTone: "aggressive",
    statLabels: {
      accuracy: "Strike Accuracy",
      stability: "Guard Stability",
      timing: "Punch Timing",
      expressiveness: "Ring Presence",
      power: "Strike Power",
    },
    challengeName: "Challenge",
    challengeNames: [
      "Shadow Boxer",
      "Iron Fist",
      "Ring General",
      "KO Artist",
      "Champion Striker",
    ],
    bgMusic: "/sounds/boxing-beat.mp3",
    rhythmBPM: 80,
    scoringWeights: WEIGHTS.boxing,
    mediaPipeTasks: ["pose", "hands", "gesture"] as MediaPipeTask[],
    subDisciplines: BOXING_SUB_DISCIPLINES,
    drills: [
      drill("bx-jab", "Jab Drill", "100 jabs – speed and accuracy", 1, 90),
      drill("bx-1-2", "Jab-Cross", "50 combinations at full speed", 1, 90),
      drill("bx-1-2-3", "3-Punch Combo", "Jab-Cross-Hook sequence", 2, 120),
      drill("bx-defense", "Slip & Counter", "Head movement + counter", 3, 150),
      drill(
        "bx-full",
        "Full 3-Min Round",
        "Complete boxing round simulation",
        5,
        180,
      ),
    ],
  },
  {
    id: "dance",
    name: "Dance",
    icon: "Music",
    color: "#c084fc",
    glow: "rgba(192,132,252,0.4)",
    bg: "rgba(192,132,252,0.08)",
    coachingTone: "rhythmic",
    statLabels: {
      accuracy: "Move Precision",
      stability: "Body Control",
      timing: "Rhythm Match",
      expressiveness: "Artistic Quality",
      power: "Dynamics",
    },
    challengeName: "Challenge",
    challengeNames: [
      "Groove Starter",
      "Floor Boss",
      "Rhythm Master",
      "Stage Presence",
      "Icon",
    ],
    bgMusic: "/sounds/dance-beat.mp3",
    rhythmBPM: 100,
    scoringWeights: WEIGHTS.dance,
    mediaPipeTasks: ["pose", "hands", "holistic"] as MediaPipeTask[],
    subDisciplines: DANCE_SUB_DISCIPLINES,
    drills: [
      drill(
        "dn-basic",
        "Basic Groove",
        "Step-touch with shoulder accent",
        1,
        120,
        100,
      ),
      drill(
        "dn-arm",
        "Arm Styling",
        "Expressive arm choreography",
        2,
        150,
        100,
      ),
      drill(
        "dn-combo",
        "8-Count Combo",
        "Full 8-count choreography",
        3,
        180,
        100,
      ),
      drill("dn-floor", "Floor Work", "Level changes sequence", 4, 200, 100),
      drill(
        "dn-routine",
        "Full Routine",
        "3-min complete performance",
        5,
        180,
        100,
      ),
    ],
  },
  {
    id: "yoga",
    name: "Yoga",
    icon: "Flower2",
    color: "#34d399",
    glow: "rgba(52,211,153,0.4)",
    bg: "rgba(52,211,153,0.08)",
    coachingTone: "spiritual",
    statLabels: {
      accuracy: "Pose Alignment",
      stability: "Balance Hold",
      timing: "Breath Flow",
      expressiveness: "Mindful Presence",
      power: "Core Strength",
    },
    challengeName: "Practice",
    challengeNames: [
      "Seeker",
      "Grounded",
      "Aligned",
      "Flow State",
      "Enlightened",
    ],
    bgMusic: "/sounds/yoga-ambient.mp3",
    rhythmBPM: 40,
    scoringWeights: WEIGHTS.yoga,
    mediaPipeTasks: ["pose", "face"] as MediaPipeTask[],
    subDisciplines: YOGA_SUB_DISCIPLINES,
    drills: [
      drill(
        "yg-sun",
        "Sun Salutation A",
        "Classic 12-pose sequence",
        1,
        180,
        40,
      ),
      drill("yg-warrior", "Warrior Series", "Warrior I, II, III", 2, 200, 40),
      drill(
        "yg-balance",
        "Balance Poses",
        "Tree, Eagle, Dancer",
        3,
        240,
        undefined,
      ),
      drill(
        "yg-invert",
        "Inversions",
        "Headstand and handstand prep",
        4,
        200,
        undefined,
      ),
      drill("yg-flow", "Advanced Flow", "Full vinyasa practice", 5, 360, 48),
    ],
  },
  {
    id: "martialarts",
    name: "Martial Arts",
    icon: "Zap",
    color: "#f87171",
    glow: "rgba(248,113,113,0.4)",
    bg: "rgba(248,113,113,0.08)",
    coachingTone: "technical",
    statLabels: {
      accuracy: "Technique Form",
      stability: "Stance Stability",
      timing: "Strike Timing",
      expressiveness: "Martial Spirit",
      power: "Strike Power",
    },
    challengeName: "Challenge",
    challengeNames: [
      "White Belt",
      "Yellow Belt",
      "Green Belt",
      "Black Belt",
      "Sensei",
    ],
    bgMusic: "/sounds/martial-beat.mp3",
    rhythmBPM: 80,
    scoringWeights: WEIGHTS.martial,
    mediaPipeTasks: ["pose", "hands", "gesture"] as MediaPipeTask[],
    subDisciplines: MARTIAL_ARTS_SUB_DISCIPLINES,
    drills: [
      drill("ma-kata", "Basic Kata", "Fundamental form sequence", 1, 120, 80),
      drill(
        "ma-kick",
        "Kick Combination",
        "Front, side, roundhouse",
        2,
        150,
        100,
      ),
      drill(
        "ma-combo",
        "10-Move Combo",
        "Full combination sequence",
        3,
        180,
        88,
      ),
      drill(
        "ma-sparring",
        "Sparring Drill",
        "Attack and defence sequences",
        4,
        200,
        90,
      ),
      drill(
        "ma-master",
        "Master Form",
        "Advanced competition form",
        5,
        300,
        80,
      ),
    ],
  },
  {
    id: "gymnastics",
    name: "Gymnastics",
    icon: "Timer",
    color: "#f472b6",
    glow: "rgba(244,114,182,0.4)",
    bg: "rgba(244,114,182,0.08)",
    coachingTone: "technical",
    statLabels: {
      accuracy: "Form Precision",
      stability: "Core Stability",
      timing: "Execution Timing",
      expressiveness: "Artistry",
      power: "Explosive Power",
    },
    challengeName: "Routine",
    challengeNames: ["Apprentice", "Flexible", "Agile", "Elite", "Olympic"],
    bgMusic: "/sounds/gymnastics-ambient.mp3",
    rhythmBPM: 80,
    scoringWeights: WEIGHTS.gymnastics,
    mediaPipeTasks: ["pose", "holistic"] as MediaPipeTask[],
    subDisciplines: [],
    drills: [
      drill("gm-cart", "Cartwheel", "Clean cartwheel technique", 1, 90),
      drill("gm-bridge", "Bridge & Backbend", "Spinal flexibility", 2, 120),
      drill("gm-round", "Round Off", "Round off to back handspring", 3, 150),
      drill("gm-tumble", "Tumbling Run", "Full tumbling sequence", 4, 180),
      drill(
        "gm-routine",
        "Floor Routine",
        "Competition floor exercise",
        5,
        300,
        80,
      ),
    ],
  },
  {
    id: "fitness",
    name: "Fitness",
    icon: "Dumbbell",
    color: "#60a5fa",
    glow: "rgba(96,165,250,0.4)",
    bg: "rgba(96,165,250,0.08)",
    coachingTone: "motivational",
    statLabels: {
      accuracy: "Form Quality",
      stability: "Core Stability",
      timing: "Rep Timing",
      expressiveness: "Intensity",
      power: "Output Power",
    },
    challengeName: "Challenge",
    challengeNames: ["Active", "Fit", "Athletic", "Shredded", "Peak"],
    bgMusic: "/sounds/fitness-beat.mp3",
    rhythmBPM: 128,
    scoringWeights: WEIGHTS.fitness,
    mediaPipeTasks: ["pose"] as MediaPipeTask[],
    subDisciplines: [],
    drills: [
      drill(
        "ft-squat",
        "Squat & Press",
        "Compound movement fundamentals",
        1,
        120,
        80,
      ),
      drill(
        "ft-burpee",
        "Burpee Drill",
        "Full-body explosive movement",
        2,
        150,
        100,
      ),
      drill("ft-hiit", "HIIT Circuit", "5-exercise circuit", 3, 200, 128),
      drill(
        "ft-complex",
        "Strength Complex",
        "Multi-movement sequence",
        4,
        200,
        100,
      ),
      drill(
        "ft-peak",
        "Peak Protocol",
        "Elite performance sequence",
        5,
        300,
        128,
      ),
    ],
  },
  {
    id: "bodybuilding",
    name: "Bodybuilding",
    icon: "User",
    color: "#fbbf24",
    glow: "rgba(251,191,36,0.4)",
    bg: "rgba(251,191,36,0.08)",
    coachingTone: "technical",
    statLabels: {
      accuracy: "Pose Quality",
      stability: "Muscle Control",
      timing: "Transition Speed",
      expressiveness: "Stage Presence",
      power: "Muscle Definition",
    },
    challengeName: "Pose-Down",
    challengeNames: ["Novice", "Amateur", "Competitor", "Pro", "IFBB Pro"],
    bgMusic: "/sounds/gym-beat.mp3",
    rhythmBPM: 60,
    scoringWeights: WEIGHTS.bodybuilding,
    mediaPipeTasks: ["pose", "face"] as MediaPipeTask[],
    subDisciplines: [],
    drills: [
      drill(
        "bb-mandatory",
        "Mandatory Poses",
        "8 mandatory poses sequence",
        1,
        120,
      ),
      drill(
        "bb-symmetry",
        "Symmetry Round",
        "Quarter turns assessment",
        2,
        150,
      ),
      drill(
        "bb-classic",
        "Classic Physique",
        "Vacuum and classic poses",
        3,
        180,
      ),
      drill("bb-routine", "Posing Routine", "90-second routine", 4, 200),
      drill(
        "bb-stage",
        "Stage Performance",
        "Full competition presentation",
        5,
        300,
      ),
    ],
  },
  {
    id: "parkour",
    name: "Parkour",
    icon: "Activity",
    color: "#a78bfa",
    glow: "rgba(167,139,250,0.4)",
    bg: "rgba(167,139,250,0.08)",
    coachingTone: "motivational",
    statLabels: {
      accuracy: "Landing Precision",
      stability: "Body Control",
      timing: "Flow Timing",
      expressiveness: "Fluidity",
      power: "Explosive Power",
    },
    challengeName: "Run",
    challengeNames: [
      "Traceur",
      "Runner",
      "Vaulter",
      "Freerunner",
      "Urban Legend",
    ],
    bgMusic: "/sounds/parkour-beat.mp3",
    rhythmBPM: 100,
    scoringWeights: {
      accuracy: 0.3,
      stability: 0.2,
      timing: 0.2,
      expressiveness: 0.1,
      power: 0.15,
      balance: 0.05,
    },
    mediaPipeTasks: ["pose", "object"] as MediaPipeTask[],
    subDisciplines: [],
    drills: [
      drill("pk-prec", "Precision Jump", "Accurate target jumping", 1, 90),
      drill("pk-vault", "Vault Drill", "Kong and speed vault", 2, 120),
      drill("pk-cat", "Cat Balance", "Quadrupedal movement", 3, 150),
      drill("pk-flow", "Flow Sequence", "Connected movement flow", 4, 180),
      drill("pk-urban", "Urban Run", "Obstacle course simulation", 5, 300),
    ],
  },
  {
    id: "calisthenics",
    name: "Calisthenics",
    icon: "Zap",
    color: "#2dd4bf",
    glow: "rgba(45,212,191,0.4)",
    bg: "rgba(45,212,191,0.08)",
    coachingTone: "technical",
    statLabels: {
      accuracy: "Form Precision",
      stability: "Static Hold",
      timing: "Movement Cadence",
      expressiveness: "Skill Execution",
      power: "Body Strength",
    },
    challengeName: "Skill",
    challengeNames: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Expert",
      "Street Elite",
    ],
    bgMusic: "/sounds/cali-beat.mp3",
    rhythmBPM: 60,
    scoringWeights: WEIGHTS.calisthenics,
    mediaPipeTasks: ["pose"] as MediaPipeTask[],
    subDisciplines: [],
    drills: [
      drill(
        "cl-pullpush",
        "Pull & Push",
        "Pull-ups and push-ups fundamentals",
        1,
        120,
      ),
      drill("cl-lsit", "L-Sit Hold", "Isometric L-sit progression", 2, 150),
      drill("cl-muscle", "Muscle Up Drill", "Muscle up technique", 3, 180),
      drill("cl-planche", "Planche Prep", "Planche lean progressions", 4, 200),
      drill("cl-lever", "Front Lever", "Full front lever performance", 5, 240),
    ],
  },
  {
    id: "pilates",
    name: "Pilates",
    icon: "Wind",
    color: "#fb7185",
    glow: "rgba(251,113,133,0.4)",
    bg: "rgba(251,113,133,0.08)",
    coachingTone: "calm",
    statLabels: {
      accuracy: "Movement Control",
      stability: "Core Engagement",
      timing: "Breath Sync",
      expressiveness: "Precision",
      power: "Powerhouse Strength",
    },
    challengeName: "Series",
    challengeNames: [
      "Fundamentals",
      "Intermediate",
      "Advanced",
      "Expert",
      "Master",
    ],
    bgMusic: "/sounds/pilates-ambient.mp3",
    rhythmBPM: 52,
    scoringWeights: {
      accuracy: 0.3,
      stability: 0.25,
      timing: 0.2,
      expressiveness: 0.1,
      power: 0.05,
      balance: 0.1,
    },
    mediaPipeTasks: ["pose", "face"] as MediaPipeTask[],
    subDisciplines: [],
    drills: [
      drill(
        "pl-hundred",
        "The Hundred",
        "Classic Pilates breathing exercise",
        1,
        120,
        52,
      ),
      drill("pl-rollup", "Roll Up Series", "Spinal articulation", 2, 150, 52),
      drill(
        "pl-circle",
        "Single Leg Circles",
        "Hip mobility and control",
        3,
        180,
        48,
      ),
      drill("pl-teaser", "Teaser Prep", "Advanced core control", 4, 200, 48),
      drill(
        "pl-full",
        "Full Mat Sequence",
        "Complete classical routine",
        5,
        300,
        52,
      ),
    ],
  },
];

// ─── LOOKUP FUNCTIONS ──────────────────────────────────────────────────────────

export const getDiscipline = (id: DisciplineId): Discipline =>
  DISCIPLINES.find((d) => d.id === id) ?? DISCIPLINES[0];

export const getAllDrills = (id: DisciplineId): Drill[] =>
  getDiscipline(id).drills;

export const getSubDiscipline = (id: string): SubDiscipline | undefined =>
  DISCIPLINES.flatMap((d) => d.subDisciplines).find((s) => s.id === id);

export const getDrillById = (
  disciplineId: DisciplineId,
  drillId: string,
): Drill | undefined =>
  getDiscipline(disciplineId).drills.find((d) => d.id === drillId);

export const getDisciplineList = (): Discipline[] => DISCIPLINES;

export const getSubDisciplines = (
  disciplineId: DisciplineId,
): SubDiscipline[] => getDiscipline(disciplineId).subDisciplines;

export const DISCIPLINE_IDS = DISCIPLINES.map((d) => d.id) as DisciplineId[];

// ─── EXTRA LOOKUP HELPERS ─────────────────────────────────────────────────────

import { TIERS } from "./gamification";

export const getTier = (id: TierId): Tier =>
  TIERS.find((t) => t.id === id) ?? TIERS[0];

export const getNextTier = (id: TierId): Tier | null => {
  const idx = TIERS.findIndex((t) => t.id === id);
  return idx >= 0 && idx < TIERS.length - 1 ? TIERS[idx + 1] : null;
};

export const getTierProgress = (xp: number, tierId: TierId): number => {
  const curr = getTier(tierId);
  const next = getNextTier(tierId);
  if (!next) return 100;
  return Math.round(((xp - curr.xpMin) / (next.xpMin - curr.xpMin)) * 100);
};

// Alias for legacy imports
export const DISCIPLINE_LIST = DISCIPLINES;
